In [4]:
# Creating a tensor 
import torch
x=torch.arange(1, 10, 1).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [6]:
# Indexing value goes outer dimension -> Inner Dimension

In [8]:
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket:\n{x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:
tensor([1, 2, 3])
Third square bracket: 1


In [9]:
# : is used to specify all values in the dimension and then , is used to add another dimension

In [10]:
x[: ,0]

tensor([[1, 2, 3]])

In [11]:
# Get all values of 0th & 1st dimension but only index of 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [12]:
# Get all values of the 0 dimension but only the 1 index valuee of the 1st & 2nd dimension
x[:, 1, 1]

tensor([5])

In [18]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 1, 0:2]

tensor([4, 5])