In [ ]:
import torch
from torch import nn
import matplotlib as mpl
import matplotlib.pyplot as plt

plt.rcParams.update({
    "figure.facecolor":"black",
    "axes.facecolor":"black",
    "axes.edgecolor":"orange",
    "xtick.color":"red",
    "ytick.color":"yellow",
    "legend.labelcolor":"linecolor"
})
plt.plot(range(10))

torch.__version__

'2.2.1+cu118'

In [ ]:
# Now we'll use linear regression to create the data with known parameters(things that can be learned by a model) and then we'll
# use PyTorch to see if we can build model to estimate these parameters using gradient descent 

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

(40, 40, 10, 10)

In [1]:
# Create known parameters
weight =.7
bias =.3
import torch
# Create data
start = 0
end = 1
step = .02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight* X + bias
X[:10], y[:10]
# Now we are moving forward towards building a model that can learn the relationship between X (features) and y(labels)
# Creating manual train test split
train_split = int(.8* len(X)) #80% of data used for training set, 20% for testing
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]
len(X_train), len(y_train), len(X_test), len(y_test)
import matplotlib.pyplot as plt
# Till our data is just nos. on page now creating a function to visualize it
def plot_predictions(train_data=X_train, 
                   train_labels=y_train,
                    test_data=X_test,
                    test_labels=y_test,
                    predictions=None
                   ):
    #     Plots training data, test data and compares predictions 
    plt.figure(figsize=(10, 7))
    # Plot training data in blue
    plt.scatter(train_data, train_labels, c="b", s=4, label="Training Data")
    #Plot test data in green
    plt.scatter(test_data, test_labels, c="g", s=4, label="Testing Data")
    if predictions is not None:
        #Plot the predictions in Red (predictions were made on the test datat)
        plt.scatter(test_data, predictions, c="r", s=4, label="Predictions")
    #Show the legend
    plt.legend(prop={"size":14})


In [ ]:
plot_predictions()

In [5]:
# Creating a Linear RegressionModel(nn.Module):
import torch
from torch import nn
class LinearRegressionModel(nn.Module): #<---almost everythings in PyTorch is nn.Module(neural network type)
    # arg--->nn.Module contains all the building blocks for neural networks
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1, dtype=torch.float), requires_grad=True)
        # PyTorch lobes float32 by default 
        # True represents that value can be updated via gradient descent method
        self.bias = nn.Parameter(torch.randn(1, dtype=torch.float), requires_grad=True)
    # Forward defines the computation in the model
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # any subclass of nn.Module needs to override forward() method
#         x is the input data
        return self.weights*x + self.bias
        

In [6]:
# # PyTorch Modules
# # torch.nn: contains all the building blocks for computational graphs
# torch.nn.Parameter: stores tensors that can be used with nn.Module. if requires_grad=True gradients(used for updating model 
#  parameter via Gradient Descent) are calculated automatically.
# torch.nn.Module:base class for all neural network modules, all the building blocks for neural networks are subclasses. if you
#  are building a neural network in PyTorch, your models should subclass nn.Module
# torch.optim: contains various optimization algorithm
# def forward() all nn.module subclass requires a forward() method defines the future required computation.

In [7]:
# # Checking the contents of the PyTorch model
# Let's create a model instance with the class we've made and check it's parameters usings
# .parameters()
# Manually setting seed since nn.Parameter are randomly initialized
torch.manual_seed(42)
# Creating an instance of the class
model_0 = LinearRegressionModel()
# Checkiing the nn.Parameter within the nn.Module subclass we created
list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [8]:
#Listing the named parameters
model_0.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [10]:
# Making predictions using torch.inference_mode()
with torch.inference_mode():
    y_preds = model_0(X_test)

NameError: name 'X_test' is not defined

In [11]:
# torch.inference_mode() & torch.no_grad() do similar things

In [12]:
# Chcking the predictions
print(f"Number of testing samples: {len(X_test)}")
print(f"Number of predictions made: {len(y_preds)}")
print(f"Predicted value: \n{y+preds}")

NameError: name 'X_test' is not defined

In [ ]:
# Creating the loss function
loss_fn =nn.L1Loss()
optimizer = torch.optim.SGD(params=model_0.parameters(), lr=.01)